### ISSUE TITLE
Linkedin button does not go to linkedin 

### ISSUE THREAD

**Issue by DylanBozarth** [mvstoyan/mvstoyan#1]
Hi Marina, the linkedin button links to the button itself instead of to your linkedin. You need to wrap the image in an <a> tag

**Comment by mvstoyan** [comment]
> Hi Marina, the linkedin button links to the button itself instead of to your linkedin. You need to wrap the image in an tag

Thank you for letting me know about the issue. I really appreciate it, Dylon.
